### ISSUE TITLE
pwa: Update the main text now that push notifications are supported

### ISSUE THREAD

**Issue by AlexITC** [wiringbits/cazadescuentos#23]
The current text says that notifications aren't supported, which isn't true anymore, now, they aren't supported only in Safari, let's update the text accordingly.

**Comment by AlexARNcode** [comment]
Hi Alex, on what file exactly is this change needed ? I can do it if you want.

**Comment by AlexITC** [comment]
Right now the text is in Spanish, I haven't prepared any text but it certainly needs to be outdated as it claims that there is no support for notifications.

**Comment by SolKuczala** [comment]
hi! I will try it, I understand Spanish

**Comment by SolKuczala** [comment]
To be sure, is it the part that talks about the phone notifications? "no recibirás notificaciones en tu celular".

**Comment by AlexITC** [comment]
Exactly, now, those are enabled unless you are in iOS (Safari).

**Comment by AlexITC** [comment]
Now, what would be ideal is to detect the browser, and display such text only if it's Safari.

**Comment by SolKuczala** [comment]
> Now, what would be ideal is to detect the browser, and display such text only if it's Safari.

I imagined that. I'll see if I can investigate on how to detect browsers and write it in Scala, frankly, I've never used it. So if anyone has it easily can give it a try :+1:

**Comment by AlexITC** [comment]
It isn't that difficult, it's mostly adding the npm dependency to detect browsers (with the proper typescript definition) to the `build.sbt`, and then, invoke that from the rendering function.

**Comment by SolKuczala** [comment]
Just because curious, I was wondering if it has to be a "lazy val" like this in pwa/build.bst: `lazy val reactNpmDeps: Project => Project =
  _.settings(
    stTypescriptVersion := "3.9.3",
    stIgnore += "react-proxy",
    Compile / npmDependencies ++= Seq(
      "react" -> "16.13.1",
      "react-dom" -> "16.13.1",
      "@types/react" -> "16.9.42",
      "@types/react-dom" -> "16.9.8",
      "csstype" -> "2.6.11",
      "@types/prop-types" -> "15.7.3",
      "react-proxy" -> "1.1.8"
    )
  )`
or if directly there. Then it will need this >> https://www.npmjs.com/package/detect-browser but in typescript (don't know where has to be in pwa). And for rendering, I'm lost with React also :sweat_smile: , but yes, the general concept to fix it is not complex.

**Comment by AlexITC** [comment]
The lazy val is a common usage in sbt build files, it should work without it, also, the `detect-browser` seems to already have types defined for TypeScript, which get converted automatically to Scala.

**Comment by AlexITC** [comment]
@SolKuczala FYI: The current master already includes the browser-detect package.
