### ISSUE TITLE
Diferencia entre mercadolibre.com.mx y articulo.mercadolibre.com

### ISSUE THREAD

**Issue by dtejedavilleda** [wiringbits/cazadescuentos#27]
Hola, quiero felicitarte por tu gran trabajo en cazadescuentos.
Cuando agregas un articulo de mercadolibre.com.mx este se pone con un icono rojo.
![imagen](https://user-images.githubusercontent.com/24535780/97503144-1cfbe580-193a-11eb-9b0a-9ef2cfbac90c.png) y en la URL aparece https://www.mercadolibre.com.mx/MLM-759886987-silabario-movil-didactico-silabas-didacticas-_JM#position=3&type=item&tracking_id=aa647027-b0a8-43df-b88f-3ed22c3c8cc7 y te aparece "Parece que esta página no existe"
Nota la diferencia de la original https://articulo.mercadolibre.com.mx/MLM-759886987-silabario-movil-didactico-silabas-didacticas-_JM#position=3&type=item&tracking_id=a84a2330-8caa-47b0-a85a-4643780a7c0b
Pasa en Mozilla Firefox 82.0.2 y Google Chrome  86.0.4240.111 
De antemano mil gracias.

**Comment by AlexITC** [comment]
Hola, primero que nada, agradezco tu comentario, parece un bug que solo pasa en la extensión pues en https://app.cazadescuentos.net me funciona bien, te notificare cuando este arreglado.

**Comment by AlexITC** [comment]
He probado lo mismo con la versión actual en Github, y el problema ya no existe, puedes probar tu mismo compilando la extensión, o puedes esperar al siguiente release.

**Comment by dtejedavilleda** [comment]
Muchas gracias por tu tiempo y tu respuesta. Excelente tarde.

**Comment by AlexITC** [comment]
@dtejedavilleda Finalemente se ha actualizado la app en chrome/firefox, podrías verificar por favor? no puedo reproducirlo mas.

**Comment by dtejedavilleda** [comment]
@AlexITC Buenas tardes. Gracias. He verificado y no aparece el error. Muchas gracias y felicidades por tu gran trabajo. :)
